package ExpoModule;

/**
* ExpoModule/ExpoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Expo.idl
* Friday, April 1, 2022 5:08:18 PM ICT
*/

public final class ExpoHolder implements org.omg.CORBA.portable.Streamable
{
  public ExpoModule.Expo value = null;

  public ExpoHolder ()
  {
  }

  public ExpoHolder (ExpoModule.Expo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ExpoModule.ExpoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ExpoModule.ExpoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ExpoModule.ExpoHelper.type ();
  }

}
