package ExpoModule;


/**
* ExpoModule/ExpoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Expo.idl
* Friday, April 1, 2022 5:08:18 PM ICT
*/

abstract public class ExpoHelper
{
  private static String  _id = "IDL:ExpoModule/Expo:1.0";

  public static void insert (org.omg.CORBA.Any a, ExpoModule.Expo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ExpoModule.Expo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ExpoModule.ExpoHelper.id (), "Expo");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ExpoModule.Expo read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ExpoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ExpoModule.Expo value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ExpoModule.Expo narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ExpoModule.Expo)
      return (ExpoModule.Expo)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ExpoModule._ExpoStub stub = new ExpoModule._ExpoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ExpoModule.Expo unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ExpoModule.Expo)
      return (ExpoModule.Expo)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ExpoModule._ExpoStub stub = new ExpoModule._ExpoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
