package ExpoModule;


/**
* ExpoModule/ExpoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Expo.idl
* Friday, April 1, 2022 5:08:18 PM ICT
*/

public interface ExpoOperations 
{
  int expo (int a, int b);
} // interface ExpoOperations
